---
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: training
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            image: training
            env:
            - name: TF_MODEL_DIR
              value: s3://kubeflow/inception
            - name: TF_EXPORT_DIR
              value: s3://kubeflow/inception/export
            - name: TF_BATCH_SIZE
              value: '100'
            - name: TF_TRAIN_STEPS
              value: '200'
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: minio123
            - name: AWS_REGION
              value: us-west-1
            - name: S3_REGION
              value: us-east-1
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: S3_ENDPOINT
              value: minio-service.kubeflow.svc:9000
            - name: TF_CPP_MIN_LOG_LEVEL
              value: "1"
          restartPolicy: OnFailure
